import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {Plus,Trash2,Edit3,CheckCircle2,Clock3,AlertCircle,ListChecks} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const api=axios.create({baseURL:API});
const emptyProject={name:'',description:'',deadline:'',status:'Planning'};
const emptyTask={title:'',description:'',assignee:'',deadline:'',status:'To Do',priority:'Medium'};
const fmt=d=>d?new Date(d).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'No deadline';

function App(){
 const [projects,setProjects]=useState([]),[tasks,setTasks]=useState([]),[selected,setSelected]=useState(null),[showProject,setShowProject]=useState(false),[showTask,setShowTask]=useState(false),[editing,setEditing]=useState(null),[projectForm,setProjectForm]=useState(emptyProject),[taskForm,setTaskForm]=useState(emptyTask),[filter,setFilter]=useState('All'),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [p,t]=await Promise.all([api.get('/projects'),api.get('/tasks')]);setProjects(p.data);setTasks(t.data);if(selected)setSelected(p.data.find(x=>x._id===selected._id)||null);}finally{setLoading(false)}};
 useEffect(()=>{load().catch(console.error)},[]);
 const selectedTasks=useMemo(()=>tasks.filter(t=>t.projectId===selected?._id && (filter==='All'||t.status===filter)),[tasks,selected,filter]);
 const progress=selected?Math.round((tasks.filter(t=>t.projectId===selected._id&&t.status==='Completed').length/Math.max(1,tasks.filter(t=>t.projectId===selected._id).length))*100):0;
 const saveProject=async e=>{e.preventDefault(); if(editing) await api.put('/projects/'+editing._id,projectForm); else await api.post('/projects',projectForm); setShowProject(false);setEditing(null);setProjectForm(emptyProject);await load()};
 const saveTask=async e=>{e.preventDefault();const body={...taskForm,projectId:selected._id};if(editing) await api.put('/tasks/'+editing._id,body); else await api.post('/tasks',body);setShowTask(false);setEditing(null);setTaskForm(emptyTask);await load()};
 const deleteProject=async id=>{if(confirm('Delete this project and its tasks?')){await api.delete('/projects/'+id);if(selected?._id===id)setSelected(null);await load()}};
 const deleteTask=async id=>{if(confirm('Delete this task?')){await api.delete('/tasks/'+id);await load()}};
 const openEditProject=p=>{setEditing(p);setProjectForm({...p,deadline:p.deadline?.slice(0,10)||''});setShowProject(true)};
 const openEditTask=t=>{setEditing(t);setTaskForm({...t,deadline:t.deadline?.slice(0,10)||''});setShowTask(true)};
 return <div className="app"><header><div><h1>ProjectFlow</h1><p>Plan projects, assign tasks, and track progress.</p></div><button className="primary" onClick={()=>{setEditing(null);setProjectForm(emptyProject);setShowProject(true)}}><Plus size={18}/> New Project</button></header>
 <main>{loading?<div className="empty">Loading...</div>:<div className="layout"><aside className="sidebar"><div className="sideTitle">Projects <span>{projects.length}</span></div>{projects.map(p=><button key={p._id} className={'projectItem '+(selected?._id===p._id?'active':'')} onClick={()=>setSelected(p)}><div><b>{p.name}</b><small>{p.status} · {fmt(p.deadline)}</small></div><span className="dot"/></button>)}{!projects.length&&<div className="hint">Create your first project.</div>}</aside>
 <section className="content">{!selected?<div className="empty"><ListChecks size={42}/><h2>Select a project</h2><p>Create a project or select one from the sidebar to manage its tasks.</p></div>:<><div className="projectHead"><div><div className="eyebrow">PROJECT</div><h2>{selected.name}</h2><p>{selected.description||'No description provided.'}</p><div className="meta">Deadline: <b>{fmt(selected.deadline)}</b> · Status: <b>{selected.status}</b></div></div><div className="actions"><button onClick={()=>openEditProject(selected)}><Edit3 size={16}/> Edit</button><button className="danger" onClick={()=>deleteProject(selected._id)}><Trash2 size={16}/> Delete</button></div></div>
 <div className="progressCard"><div><b>Overall progress</b><strong>{progress}%</strong></div><div className="bar"><i style={{width:progress+'%'}}/></div></div>
 <div className="taskToolbar"><div><h3>Tasks</h3><span>{selectedTasks.length} shown</span></div><div className="filters">{['All','To Do','In Progress','Completed'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}<button className="primary" onClick={()=>{setEditing(null);setTaskForm(emptyTask);setShowTask(true)}}><Plus size={16}/> Add Task</button></div></div>
 <div className="tasks">{selectedTasks.map(t=><article className="task" key={t._id}><div className={'statusIcon '+t.status.replaceAll(' ','')} >{t.status==='Completed'?<CheckCircle2/>:t.status==='In Progress'?<Clock3/>:<AlertCircle/>}</div><div className="taskBody"><div className="taskTop"><h4>{t.title}</h4><span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span></div><p>{t.description||'No description.'}</p><div className="taskMeta">Assignee: <b>{t.assignee||'Unassigned'}</b> · Due: <b>{fmt(t.deadline)}</b> · <b>{t.status}</b></div></div><div className="taskActions"><button onClick={()=>openEditTask(t)}><Edit3 size={15}/></button><button onClick={()=>deleteTask(t._id)}><Trash2 size={15}/></button></div></article>)}{!selectedTasks.length&&<div className="empty small"><ListChecks size={30}/><p>No tasks match this filter.</p></div>}</div></>}</section></div>}</main>
 {showProject&&<Modal title={editing?'Edit Project':'Create Project'} onClose={()=>setShowProject(false)}><form onSubmit={saveProject}>{<Field label="Project name" value={projectForm.name} onChange={v=>setProjectForm({...projectForm,name:v})} required/>}<Field label="Description" value={projectForm.description} onChange={v=>setProjectForm({...projectForm,description:v})} textarea/><div className="two"><Field label="Deadline" type="date" value={projectForm.deadline} onChange={v=>setProjectForm({...projectForm,deadline:v})}/><Select label="Status" value={projectForm.status} onChange={v=>setProjectForm({...projectForm,status:v})} options={['Planning','In Progress','Completed']}/></div><button className="primary full">Save Project</button></form></Modal>}
 {showTask&&<Modal title={editing?'Edit Task':'Add Task'} onClose={()=>setShowTask(false)}><form onSubmit={saveTask}><Field label="Task title" value={taskForm.title} onChange={v=>setTaskForm({...taskForm,title:v})} required/><Field label="Description" value={taskForm.description} onChange={v=>setTaskForm({...taskForm,description:v})} textarea/><div className="two"><Field label="Assignee" value={taskForm.assignee} onChange={v=>setTaskForm({...taskForm,assignee:v})}/><Field label="Deadline" type="date" value={taskForm.deadline} onChange={v=>setTaskForm({...taskForm,deadline:v})}/></div><div className="two"><Select label="Status" value={taskForm.status} onChange={v=>setTaskForm({...taskForm,status:v})} options={['To Do','In Progress','Completed']}/><Select label="Priority" value={taskForm.priority} onChange={v=>setTaskForm({...taskForm,priority:v})} options={['Low','Medium','High']}/></div><button className="primary full">Save Task</button></form></Modal>}
 </div>
}
const Field=({label,value,onChange,type='text',textarea,required})=><label>{label}{textarea?<textarea value={value} onChange={e=>onChange(e.target.value)} required={required}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/>}</label>;
const Select=({label,value,onChange,options})=><label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;
const Modal=({title,onClose,children})=><div className="overlay"><div className="modal"><div className="modalHead"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>;
createRoot(document.getElementById('root')).render(<App/>);
